name: obsenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - black
  - pylint
  - pandas
  - matplotlib
  - jupyterlab
  - ipykernel
  - streamlit
  - plotly
  - boto3
  - awswrangler
  - pip
  - pip:
      - great-tables