name: obsenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.7
  - black
  - pylint
  - pandas
  - numpy
  - matplotlib
  - plotnine
  - scikit-learn
  - mypy
  - jupyterlab
  - ipykernel
  - streamlit
  - great_tables
