"""
pca_kmeans.py
-------------
Generates a violence score (0-100) for each Mexican state using PCA and KMeans clustering.

Inputs:
    - s3://<BUCKET>/processed/delitos_rate/ (Parquet files generated by Glue ETL job)

Outputs:
    - s3://<BUCKET>/outputs/violence_scores.csv     (overall score per state)
    - s3://<BUCKET>/outputs/violence_scores_yearly.csv (score per state per year)

Usage:
    python pca_kmeans.py
"""

import io
import boto3
import numpy as np
import pandas as pd
from pyathena import connect
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# ── Configuration ─────────────────────────────────────────────────────────────

BUCKET = "mexico-public-safety-observatory"
ATHENA_STAGING = f"s3://{BUCKET}/athena-results/"
REGION = "us-east-1"
N_COMPONENTS = 5
N_CLUSTERS = 4
VARIANCE_THRESHOLD = 0.70


def load_data() -> pd.DataFrame:
    """
    Loads crime rate data from Athena.

    Returns:
        pd.DataFrame: DataFrame with columns
            [anio, month, entidad_nombre, tipo_delito, rate_per_100k]
    """
    conn = connect(
        s3_staging_dir=ATHENA_STAGING,
        region_name=REGION
    )

    query = """
        SELECT anio, month, entidad_nombre, tipo_delito, rate_per_100k
        FROM observatory.delitos_rate
        WHERE rate_per_100k IS NOT NULL
    """

    df = pd.read_sql(query, conn)
    print(f"Loaded {df.shape[0]:,} rows from Athena")
    return df


def build_feature_matrix(df: pd.DataFrame) -> pd.DataFrame:
    """
    Pivots data into a wide matrix of states x crime types
    using the mean rate across all months and years.

    Args:
        df: Long-format DataFrame from load_data()

    Returns:
        pd.DataFrame: Wide matrix with shape (n_states, n_crime_types)
    """
    df_pivot = df.groupby(
        ['entidad_nombre', 'tipo_delito']
    )['rate_per_100k'].mean().reset_index()

    df_wide = df_pivot.pivot(
        index='entidad_nombre',
        columns='tipo_delito',
        values='rate_per_100k'
    ).fillna(0)

    print(f"Feature matrix shape: {df_wide.shape}")
    return df_wide


def fit_pca_score(df_wide: pd.DataFrame):
    """
    Fits a StandardScaler and PCA on the feature matrix.
    Uses the first N components that explain ~70% of variance.

    Args:
        df_wide: Wide feature matrix from build_feature_matrix()

    Returns:
        scaler: Fitted StandardScaler
        pca: Fitted PCA model
        weights: Explained variance ratios for the selected components
        score_min: Minimum raw score (for normalization)
        score_max: Maximum raw score (for normalization)
        score_100: Normalized violence scores (0-100) per state
    """
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(df_wide)

    pca = PCA(n_components=N_COMPONENTS)
    X_pca = pca.fit_transform(X_scaled)

    cumulative = np.cumsum(pca.explained_variance_ratio_)
    print(f"Variance explained by {N_COMPONENTS} components: {cumulative[-1]:.1%}")

    weights = pca.explained_variance_ratio_
    raw_score = X_pca @ weights

    score_min = raw_score.min()
    score_max = raw_score.max()
    score_100 = (raw_score - score_min) / (score_max - score_min) * 100

    return scaler, pca, weights, score_min, score_max, score_100


def fit_kmeans(score_100: np.ndarray) -> np.ndarray:
    """
    Clusters states into N_CLUSTERS groups based on their violence score.

    Args:
        score_100: Normalized violence scores (0-100)

    Returns:
        np.ndarray: Cluster labels ordered by mean score
                    (0=Bajo, 1=Medio, 2=Alto, 3=Crítico)
    """
    kmeans = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
    raw_clusters = kmeans.fit_predict(score_100.reshape(-1, 1))

    # Map clusters to ordered labels by mean score
    temp = pd.DataFrame({'score': score_100, 'cluster': raw_clusters})
    cluster_means = temp.groupby('cluster')['score'].mean().sort_values()
    label_map = {
        cluster_means.index[0]: 'Bajo',
        cluster_means.index[1]: 'Medio',
        cluster_means.index[2]: 'Alto',
        cluster_means.index[3]: 'Crítico'
    }

    return pd.Series(raw_clusters).map(label_map).values


def build_yearly_scores(
    df: pd.DataFrame,
    scaler: StandardScaler,
    pca: PCA,
    weights: np.ndarray,
    score_min: float,
    score_max: float
) -> pd.DataFrame:
    """
    Computes violence scores per state per year for time series visualization.
    Uses the same scaler and PCA fitted on the full dataset.

    Args:
        df: Long-format DataFrame from load_data()
        scaler: Fitted StandardScaler
        pca: Fitted PCA model
        weights: Explained variance ratios
        score_min: Minimum raw score from full dataset
        score_max: Maximum raw score from full dataset

    Returns:
        pd.DataFrame: Columns [entidad_nombre, anio, violence_score]
    """
    df_yearly_wide = df.groupby(
        ['entidad_nombre', 'anio', 'tipo_delito']
    )['rate_per_100k'].mean().reset_index().pivot_table(
        index=['entidad_nombre', 'anio'],
        columns='tipo_delito',
        values='rate_per_100k'
    ).fillna(0)

    X_yearly_scaled = scaler.transform(df_yearly_wide)
    X_yearly_pca = pca.transform(X_yearly_scaled)
    raw_score_yearly = X_yearly_pca @ weights

    score_yearly = (raw_score_yearly - score_min) / (score_max - score_min) * 100
    score_yearly = np.clip(score_yearly, 0, 100)

    df_time_series = pd.DataFrame({
        'entidad_nombre': df_yearly_wide.index.get_level_values('entidad_nombre'),
        'anio': df_yearly_wide.index.get_level_values('anio'),
        'violence_score': score_yearly
    }).sort_values(['entidad_nombre', 'anio'])

    return df_time_series


def save_to_s3(df: pd.DataFrame, key: str) -> None:
    """
    Saves a DataFrame as Parquet to S3.

    Args:
        df: DataFrame to save
        key: S3 key (path within bucket)
    """
    s3 = boto3.client('s3')
    buffer = io.BytesIO()
    df.to_parquet(buffer, index=False, engine='pyarrow')
    buffer.seek(0)
    s3.put_object(Bucket=BUCKET, Key=key, Body=buffer.read())
    print(f"Saved s3://{BUCKET}/{key}")


def main():
    """
    Full pipeline: load → feature matrix → PCA → KMeans → save outputs.
    """
    print("── Loading data from Athena ──────────────────────────────")
    df = load_data()

    print("\n── Building feature matrix ───────────────────────────────")
    df_wide = build_feature_matrix(df)

    print("\n── Fitting PCA and computing violence scores ─────────────")
    scaler, pca, weights, score_min, score_max, score_100 = fit_pca_score(df_wide)

    print("\n── Clustering states with KMeans ─────────────────────────")
    niveles = fit_kmeans(score_100)

    df_scores = pd.DataFrame({
        'entidad_nombre': df_wide.index,
        'violence_score': score_100,
        'nivel': niveles
    }).sort_values('violence_score', ascending=False)

    print(df_scores)

    print("\n── Computing yearly scores ───────────────────────────────")
    df_yearly = build_yearly_scores(df, scaler, pca, weights, score_min, score_max)

    print("\n── Saving outputs to S3 ──────────────────────────────────")
    save_to_s3(df_scores, "outputs/violence_scores.parquet")
    save_to_s3(df_yearly, "outputs/violence_scores_yearly.parquet")

    print("\n✓ Pipeline complete")


if __name__ == "__main__":
    main()